config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'recipes#index'
  resources :recipes do
    resources :ingredients
    resources :instructions
  end

  get 'users/signup', to: 'users#new'
  resources :users, except: :new

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
  validates :qty, :unit, :ingredient, presence: true
end

app/models/instruction.rb
class Instruction < ApplicationRecord
  belongs_to :recipe
  validates :step, :instruction, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  MINIMUM_TITLE_LENGTH = 5

  has_many :ingredients, inverse_of: :recipe, dependent: :destroy
  accepts_nested_attributes_for :ingredients
  has_many :instructions, inverse_of: :recipe, dependent: :destroy
  accepts_nested_attributes_for :instructions
  validates :title, presence: true, length: { minimum: MINIMUM_TITLE_LENGTH }

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  MINIMUM_NAME_LENGTH = 4
  MAXIMUM_NAME_LENGTH = 50
  MAXIMUM_EMAIL_LENGTH = 50
  MINIMUM_PASSWORD_LENGTH = 6

  has_secure_password
  has_many :recipes, dependent: :destroy

  before_save :email_to_downcase

  validates :name, presence: true, length: { minimum: MINIMUM_NAME_LENGTH , maximum: MAXIMUM_NAME_LENGTH },
                    uniqueness: true
  validates :email, presence: true, length: { maximum: MAXIMUM_EMAIL_LENGTH },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  validates :first_name, presence: true, length: { maximum: MAXIMUM_NAME_LENGTH }
  validates :last_name, presence: true, length: { maximum: MAXIMUM_NAME_LENGTH }
  validates :password, presence: true, length: { minimum: MINIMUM_PASSWORD_LENGTH }

  private

  def email_to_downcase
    self.email = email.downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  before_action :require_login

  private

  def require_login
    unless logged_in?
      flash[:danger] = 'Please sign in to continue.'
      redirect_to login_path
    end
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  

  def new
    @recipe = Recipe.find(params[:recipe_id])
    @ingredient = @recipe.ingredients.build
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @ingredient = @recipe.ingredients.build(ingredient_params)

    if @ingredient.save
      redirect_to @recipe
    else
      render :new
    end
  end

  def destroy
    ingredient = ingredient.find(params[:id])
    ingredient.destroy

    redirect_to ingredient.article
  end

  private

  def ingredient_params
    params.require(:ingredient).permit(:qty, :unit, :ingredient)
  end
end

app/controllers/instructions_controller.rb
class InstructionsController < ApplicationController
  def new
    @recipe = Recipe.find(params[:recipe_id])
    @instruction = @recipe.instructions.build
  end

  def create
    recipe = Recipe.find(params[:recipe_id])

    instruction = recipe.instructions.build(instruction_params)

    instruction.save
    redirect_to recipe
  end

  def destroy
    instruction = instruction.find(params[:id])
    instruction.destroy

    redirect_to instruction.article
  end

  private

  def instruction_params
    params.require(:instruction).permit(:step, :instruction)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  skip_before_action :require_login, only: [:index, :show]
  before_action :find_recipe, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @recipes = Recipe.all
  end

  def show

  end

  def new
    @recipe = Recipe.new
    10.times { @recipe.ingredients.build }
    10.times { @recipe.instructions.build }
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user

    if @recipe.save
      redirect_to @recipe
    else
      render :new
    end
  end

  def edit

  end

  def update

    if @recipe.update(recipe_params)
      redirect_to @recipe
    else
      render 'edit'
    end
  end

  def destroy
    @recipe.destroy
    redirect_to recipes_path
  end

  private

  def find_recipe
    @recipe = Recipe.find(params[:id])
  end

  def correct_user
    unless equal_with_current_user?(@recipe.user)
      flash[:danger] = 'Wrong User'
      redirect_to(root_path)
    end
  end

  def recipe_params
    params.require(:recipe).permit(:title, :description,
      ingredients_attributes:[:id, :qty, :unit, :ingredient],
      instructions_attributes:[:id, :step, :instruction])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)

    if user && user.authenticate(params[:session][:password])
      log_in(user)
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, except: :show

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in(@user)
      redirect_to @user
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :first_name, :last_name,
    :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/instructions_helper.rb
module InstructionsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def logged_in?
    current_user.present?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

    def equal_with_current_user?(other_user)
    current_user == other_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ingredients/new.html.erb
<div class="container">
  <div class="columns is-multiline">
    <div class="column is-6 is-offset-3">
      <div class="content is-size-3">
        <h1><%= @recipe.title %> - New Ingredient</h1>
      </div>
    </div>

    <% if @ingredient.errors.any? %>
      <div class="column is-6 is-offset-3">
        <article class="message is-danger">
          <div class="message-body">
            <p><%= pluralize(@ingredient.errors.count, "error") %> prohibited this ingredient
            from being saved:</p>
            <br>
            <p><% @ingredient.errors.full_messages.each do |msg|%>
              <li><%= msg %></li>
            <% end%>
            </p>
          </div>
        </article>
      </div>
    <% end %>

    <div class="column is-6 is-offset-3">
      <article class="media">
        <div class="media-content">
          <%= form_with model: [@recipe, @ingredient], local: true do |form| %>
            <div class="field">
              <p class="control">
                <%= form.text_field :qty, class: "input", placeholder: 'Quantity' %>
              </p>
            </div>
            <div class="field">
              <p class="control">
                <%= form.text_field :unit, class: "input", placeholder: 'Unit' %>
              </p>
            </div>
            <div class="field">
              <p class="control">
                <%= form.text_firld :ingredient, class: "textarea", placeholder: "Add ingredient..." %>
              </p>
            </div>
            <nav class="level">
              <div class="level-left">
              </div>
              <div class="level-right">
                <div class="level-item">
                  <%= form.submit "Save", class: 'button is-info' %>
                </div>
                <div class="level-item">
                  <%= link_to "Cancel", recipe_path(@recipe), class: 'button is-light' %>
                </div>
              </div>
            </nav>
          <% end %>
        </div>
      </article>
    </div>
  </div>
</div>

app/views/instructions/new.html.erb
<div class="container">
  <div class="columns is-multiline">
    <div class="column is-6 is-offset-3">
      <div class="content is-size-3">
        <h1><%= @recipe.title %> - New Instruction</h1>
      </div>
    </div>

    <div class="column is-6 is-offset-3">
      <article class="media">
        <div class="media-content">
          <%= form_with model: [@recipe, @instruction], local: true do |form| %>
            <div class="field">
              <p class="control">
                <%= form.text_field :step, class: "input", placeholder: 'Step' %>
              </p>
            </div>
            <div class="field">
              <p class="control">
                <%= form.text_area :instruction, class: "textarea", placeholder: "Add instruction..." %>
              </p>
            </div>
            <nav class="level">
              <div class="level-left">
              </div>
              <div class="level-right">
                <div class="level-item">
                  <%= form.submit "Save", class: 'button is-info' %>
                </div>
                <div class="level-item">
                  <%= link_to "Cancel", recipe_path(@recipe), class: 'button is-light' %>
                </div>
              </div>
            </nav>
          <% end %>
        </div>
      </article>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <section class="section">
      <%= render 'shared/nav_bar' %>
      <%= render 'shared/flash' %>

      <%= yield %>
    </section>
  </body>
</html>

app/views/recipes/_form.html.erb
<% if recipe.errors.any? %>
  <div class="column is-6 is-offset-3">
    <article class="message is-danger">
      <div class="message-body">
        <p>
          <%= pluralize(recipe.errors.count, 'error') %>
          prohibited this recipe from being saved:</p>
        <br>
        <p>
        <% recipe.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </p>
      </div>
    </article>
  </div>
<% end %>

<div class="container">
  <div class="column is-multiline">
    <div class="column is-6 is-offset-3">
      <div class="content is-size-3">
        <h1> <%= heading %> </h1>
      </div>
    </div>

    <div class="column is-12">
      <%= form_with model: recipe, local: true do |form| %>
        <div class="field">
          <%= form.label :title, class: "label" %>
          <div class="control">
            <%= form.text_field :title, class: "input", placeholder: 'Title' %>
          </div>
        </div>

        <div class="field">
          <%= form.label :description, class: "label" %>
          <div class="control">
            <%= form.text_area :description, class: "textarea", placeholder: 'Description of the recipe'%>
          </div>
        </div>

        <div>
          <div class="content is-size-5">
            <h4>Ingredients:</h4>
          </div>
          <ul>
            <%= form.fields_for :ingredients do |ingredients_form| %>
              <li>
                <%= ingredients_form.label :'Quantity' %>
                <%= ingredients_form.text_field :qty %>
                <%= ingredients_form.label :unit %>
                <%= ingredients_form.text_field :unit %>
                <%= ingredients_form.label :ingredient %>
                <%= ingredients_form.text_field :ingredient %>
              </li>
            <% end %>
          </ul>
        </div>

        <div>
          <div class="content is-size-5">
            <h4>Instructions:</h4>
          </div>
          <ul>
            <%= form.fields_for :instructions do |instructions_form| %>
              <li>
                <%= instructions_form.label :step %>
                <%= instructions_form.text_field :step %>
                <%= instructions_form.label :instruction %>
                <%= instructions_form.text_area :instruction %>
              </li>
            <% end %>
          </ul>
        </div>

        <div class="field is-grouped">
          <div class="control">
            <%= form.submit "Submit", class: "button is-link" %>
          </div>
          <div class="contorl">
            <%= link_to "Cancel", cancel_path, class: "button is-link is-light" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/recipes/_recipe.html.erb
<div class="column is-6 is-offset-3">
  <div class="card">
    <% unless local_assigns[:show] %>
      <header class="card-header">
        <p class="card-header-title">
          <%= recipe.title %>
        </p>
      </header>
    <% end %>
    <div class="card-content">
      <div class="content">
        <p><%= recipe.description %></p>
      </div>
    </div>
    <footer class="card-footer">
      <% if local_assigns[:show] %>
        <%= link_to 'Back', root_path, class: "card-footer-item" %>
      <% else %>
        <%= link_to 'Show', recipe_path(recipe), class: "card-footer-item" %>
      <% end %>
      <% if logged_in? && equal_with_current_user?(recipe.user) %>
        <%= link_to 'Edit', edit_recipe_path(recipe), class: "card-footer-item" %>
      <% end %>

      <% if logged_in? && equal_with_current_user?(recipe.user) %>
        <%= link_to 'Delete', recipe_path(recipe), method: :delete,
        data: { confirm: "Are you sure you want to delete #{recipe.title} recipe?" },
        class: "card-footer-item" %>
      <% end %>
    </footer>
  </div>
</div>

app/views/recipes/edit.html.erb
<%= render 'form',
  recipe: @recipe,
  submit: 'Update Recipe',
  cancel_path: recipe_path(@recipe),
  heading: 'Edit Recipe' %>

app/views/recipes/index.html.erb
<div class="container">
  <div class="column is-multiline">
    <div class="column is-6 is-offset-3">
      <div class="content is-size-3">
        <h1>Recipes</h1>
      </div>
    </div>

    <%= render @recipes %>
  </div>
</div>

app/views/recipes/new.html.erb
<%= render 'form',
  recipe: @recipe,
  submit: 'Save Recipe',
  cancel_path: root_path,
  heading: 'New Recipe' %>

app/views/recipes/show.html.erb
<div class="container">
  <div class="column is-multiline">
    <div class="column is-6 is-offset-3">
      <div class="content is-size-3">
        <h1> <%= @recipe.title %> </h1>
      </div>
    </div>

  <%= render @recipe, show: true %>

  <div class="column is-6 is-offset-3">
    <article class="media">
      <div class="media-content">
        <div class="content">
          <p>
            <strong>INGREDIENTS</strong>
          </p>
        </div>
      </div>
    </article>
  </div>

  <% @recipe.ingredients.each do |ingredient| %>
  <div class="column is-6 is-offset-3">
    <article class="media">
      <div class="media-content">
        <div class="content">
          <p>
            <%= ingredient.qty %>
            <%= ingredient.unit %>
            <%= ingredient.ingredient %>
          </p>
        </div>
      </div>
    </article>
  </div>
  <% end %>

  <div class="column is-6 is-offset-3">
    <article class="media">
      <div class="media-content">
        <div class="content">
          <p>
            <strong>INSTRUCTIONS</strong>
          </p>
        </div>
      </div>
    </article>
  </div>

  <% @recipe.instructions.each do |instruction| %>
    <div class="column is-6 is-offset-3">
      <article class="media">
        <div class="media-content">
          <div class="content">
            <p>
              <%= instruction.step %>
              <%= instruction.instruction %>
            </p>
          </div>
        </div>
      </article>
    </div>
  <% end %>

app/views/shared/_flash.html.erb
<div class="container">
  <div class="columns is-multiline">
    <% flash.each do |name, msg| -%>

    <div class="column is-8 is-offset-2">
      <div class="notification has-text-centered is-<%= name %>">
        <%= msg %>
      </div>
    </div>

    <% end -%>
  </div>
</div>

app/views/shared/_nav_bar.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="container">
    <div class="navbar-brand">

      <%= link_to "Recipes", root_path, class: "navbar-item is-size-1" %>

      <a role="button" class="navbar-burger burger" aria-label="menu" aria-
      expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-end">
        <div class="navbar-item">
          <div class="buttons">
              <% if logged_in? %>
                <%= link_to "New Recipe", new_recipe_path, class: "button is-primary
has-text-weight-bold" %>
                <%= link_to "User Profile", user_path(current_user), class: "button is-primary
has-text-weight-bold" %>
                <%= link_to "Log Out", logout_path, method: :delete, class: "button is-
primary has-text-weight-bold"%>
              <% else %>
                <%= link_to "Log In", login_path, class: "button is-primary has-text-
weight-bold" %>
                <%= link_to "Sign Up", users_signup_path, class: "button is-primary has-
text-weight-bold" %>
              <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/users/_user.html.erb
<div class="card">
  <div class="card-content">
    <div class="media">
      <div class="media-left">
        <figure class="image is-48x48">
          <img src="https://bulma.io/images/placeholders/96x96.png" alt="Placeholder image">
        </figure>
      </div>
      <div class="media-content">
        <p class="title is-4"><%= user.name %></p>
        <p class="subtitle is-6"><%= user.first_name %></p>
        <p class="subtitle is-6"><%= user.last_name %></p>
        <p class="subtitle is-6"><%= user.email %></p>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="columns is-multiline">
    <div class="column is-6 is-offset-3">
      <div class="content is-size-3">
        <h1>New User</h1>
      </div>
    </div>

      <% if @user.errors.any? %>
        <div class="column is-6 is-offset-3">
          <article class="message is-danger">
            <div class="message-body">
              <p><%= pluralize(@user.errors.count, "error") %> prohibited this user from
being saved:</p>
              <br>
              <p>
              <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
              </p>
            </div>
          </article>
        </div>
      <% end %>

      <div class="column is-6 is-offset-3">
        <%= form_with model: @user, local: true do |form| %>
        <div class="field">
          <%= form.label :name, class: "label" %>

          <div class="control">
            <%= form.text_field :name, class: "input", placeholder: "Your name"%>
          </div>
        </div>

        <div class="field">
          <%= form.label :first_name, class: "label" %>

          <div class="control">
            <%= form.text_field :first_name, class: "input", placeholder: "Your first name"%>
          </div>
        </div>

        <div class="field">
          <%= form.label :last_name, class: "label" %>

          <div class="control">
            <%= form.text_field :last_name, class: "input", placeholder: "Your first name"%>
          </div>
        </div>

        <div class="field">
          <%= form.label :email, class: "label" %>

          <div class="control">
            <%= form.email_field :email, class: "input", placeholder: 'Your email' %>
          </div>
        </div>

        <div class="field">
          <%= form.label :password, class: "label" %>

          <div class="control">
            <%= form.password_field :password, class: "input", placeholder: 'Your
password' %>
          </div>
        </div>

        <div class="field">
          <%= form.label :password_confirmation, class: "label" %>
         <div class="control">
            <%= form.password_field :password_confirmation, class: "input", placeholder:
'Confirm password' %>
          </div>
        </div>

        <div class="field is-grouped">
          <div class="control">
            <%= form.submit "Submit", class: "button is-link" %>
          </div>

          <div class="control">
            <%= link_to "Cancel", recipes_path, class: 'button is-link is-light' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="container">
  <div class="columns is-multiline">
    <div class="column is-6 is-offset-3">
      <div class="content is-size-3">
        <h3><%= @user.name %></h3>
        <p><%= @user.email %></p>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
    <div class="columns is-multiline">
        <div class="column is-6 is-offset-3">
            <h1 class="title is-size-1">User</h1>
        </div>
        <div class="column is-6 is-offset-3">
            <%= render @user %>
        </div>
        <div class="content is-size-3">
          <table class="table">
            <% if @user.recipes.any? %>
              <tbody>
                <% @user.recipes.each do |recipe| %>
                  <tr>
                    <td><%= link_to recipe.title, recipe_path(recipe) %></td>
                  </tr>
                <% end %>
              </tbody>
            <% end %>
          </table>
        </div>
    </div>
    </div>
</div>